name: SonarCloud Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read

env:
  SONARSCANNER: "true"
  COLLECT_COVERAGE: "1"

jobs:
  build:
    permissions:
      contents: read
      security-events: write
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name && github.event.sender.login != 'dependabot[bot]' ||
      github.event_name == 'push' && !contains(github.event.head_commit.message, '[ci skip]')
    steps:
      - name: Run SonarCloud analysis
        uses: myrotvorets/composite-actions/node-sonarscan@65a2ad38ee88c348c96631c7afa0f940975d020a # master
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          test-script: "test:coverage"
